spring.mail.host=mail.ibukatech.com
spring.mail.port=587
spring.mail.username=no-reply@ibukatech.com
spring.mail.password=MunenePE.1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
mail.debug=false
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.ssl.enable=true