spring.mail.host=smtp-mail.outlook.com
spring.mail.port=587
spring.mail.username=ngangagachuru@outlook.com
spring.mail.password=12321.Png!@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
mail.debug=false