
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB




jwt.secret=23efcc8cb45c9ef9e4e6a6bb5cfba75e4ca37475d021e0cc3c33b638694575b811555affb5d5a983fb99bfdc937bc6da9dafc5b524ee847a170cfd12d696ee2a
jwt.jwtExpirationMs=86400000

encryption.password=myfuture

jwt.password.encoder.secret=mysecret
jwt.password.encoder.iteration=33
jwt.password.encoder.keylength=256
jwt.password.token.expirationMs=3e+8

#spring.mail.sender=info@equitybank.co.ke
#spring.mail.host=smtphost.ebsafrica.com
#spring.mail.port=25
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.smtp.ssl.enable=false

spring.mail.host=mail.myfuture.co.ke
spring.mail.port=587
spring.mail.sender=info@myfuture.co.ke
spring.mail.password=3Pvcp27R2f(WN@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.starttls.enable=true

mm.email.sender = info@myfuture.co.ke
mm.email.host = mail.myfuture.co.ke
mm.email.port = 587
mm.email.password = 3Pvcp27R2f(WN@
mm.email.subject = YOUR LOGIN CREDENTIALS
mm.email.greetings = <b>Dear User,</b><br/>
mm.email.signoff = <br/><br/><b>Kindly change the credentials especially password after your first sign in.</b>
mm.email.body1 = Your login credentials are : <br/> <b>Username   :   <b>
mm.email.body2 = <br/><b>Password   :   </b>
mm.email.body3 = You have requested to have your password reset for your account at Reconmaster Portal. Please visit this url to reset your password :
mm.email.body4 = <br/><p><a href="
mm.email.body5 = ">Reset Password
mm.email.body6 = </a></p><br/><p>If you received this email in error, you can safely ignore this email.</p>
mm.email.subject1 = PASSWORD RESET.
