server.port = 2024
#MySQL Configurations
spring.datasource.url=jdbc:mariadb://localhost:3306/myfuturequestionstor
spring.datasource.username=root
spring.datasource.password=MunenePE.1
spring.jpa.show-sql=true
spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.servlet.multipart.max-file-size=100000000MB
spring.servlet.multipart.max-request-size=100000000MB


#EMAILS
#Mail Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.socketFactory.class= javax.net.ssl.SSLSocketFactory
spring.mail.host=mail.myfuture.co.ke
spring.mail.port=587
spring.mail.username=no-reply@myfuture.co.ke
spring.mail.password=pteasg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.starttls.enable=true

report.appname=My Future KCPE And CBC Revision
report.logo=C:/Users/USER/AndroidStudioProjects/My-Future/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
report.path=C:/Users/USER/web/myfuturereports