server.port = 2024
#MySQL Configurations

datasource.questions.driver-class-name=org.mariadb.jdbc.Driver
datasource.questions.url=jdbc:mariadb://localhost:3306/myfuture_question_store
datasource.questions.username=root
datasource.questions.password=root

datasource.images.driver-class-name=org.mariadb.jdbc.Driver
datasource.images.url=jdbc:mariadb://localhost:3306/myfutureimages
datasource.images.username=root
datasource.images.password=root

datasource.students.driver-class-name=org.mariadb.jdbc.Driver
datasource.students.url=jdbc:mariadb://localhost:3306/myfuture_student_management
datasource.students.username=root
datasource.students.password=root


datasource.tuabudu.driver-class-name=org.mariadb.jdbc.Driver
datasource.tuabudu.url=jdbc:mariadb://localhost:3306/tuabudu
datasource.tuabudu.username=root
datasource.tuabudu.password=root


datasource.oldmyfuture.driver-class-name=org.mariadb.jdbc.Driver
datasource.oldmyfuture.url=jdbc:mariadb://localhost:3306/leadtool_myfuturemain
datasource.oldmyfuture.username=root
datasource.oldmyfuture.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.servlet.multipart.max-file-size=100000000MB
spring.servlet.multipart.max-request-size=100000000MB


#EMAILS
#Mail Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.socketFactory.class= javax.net.ssl.SSLSocketFactory
spring.mail.host=mail.myfuture.co.ke
spring.mail.port=587
spring.mail.username=info@myfuture.co.ke
spring.mail.password=3Pvcp27R2f(WN@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.starttls.enable=true

organisation.emailRegards=Regards Myfuture KCPE CBC Revision App
organisation.emailMessage=Find the attached information from our partnership
organisation.emailOrganizationName=Myfuture KCPE CBC Revision App
organisation.image_banner=C:/Users/USER/personal/My-Future/app/src/main/launcher-playstore.png
organisation.emailRemarks=Thank You.
organisation.emailOrganizationPhone=+254111723106
organisation.emailOrganizationWebsite=https://myfuture.co.ke
organisation.emailOrganizationMail=myfuturekcpe@gmail.com
organisation.from_mail=no-reply@myfuture.co.ke
organisation.company_logo_path=C:/Users/USER/personal/My-Future/app/src/main/launcher-playstore.png
organisation.emailSalutation=Dear,

report.appname=My Future KCPE And CBC Revision
report.logo=C:/Users/USER/personal/My-Future/app/src/main/launcher-playstore.png
report.path=C:/Users/USER/web/myfuturereports

